### ISSUE TITLE
Liquidation Bot: initiate collateral Liquidation

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-bot#13]
1. find underwater vaults. use https://www.letsgethai.com/#/auctions?type=COLLATERAL or SDK to find a list of vaults that can have their collateral liquidated
2. when a vault is found kick off a collateral auction by calling `liquidateSafe` on the liquidation engine
3. call max bid on the newly kicked off auction

ABIs https://github.com/hai-on-op/app/tree/main/src/abis

**Comment by pi0neerpat** [comment]
Stale
