### ISSUE TITLE
Earn: Fetch Nitro APY from API

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-bot#82]
## Issue:

- We are having difficulties calculating the APY on OD-ETH Nitropool

## Goal:

- Scrape the APY from the Nitropools page [Example here](https://app.camelot.exchange/nitro/0x626a551E910EcCA62e61DCeB37e3726C7d423185) and provide it via API to the od-app

## How:
- Scrape it with Puppeteer from the page
- Get it from Discord

**Comment by Seroxdesign** [comment]
@jahabeebs

**Comment by pi0neerpat** [comment]
See https://api.camelot.exchange/nitros

**Comment by Seroxdesign** [comment]
Done
